name: flutter_fippop
description: AI 스쿼트 트레이너 앱
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  
  # 카메라 및 ML Kit
  camera: ^0.10.5+9
  google_mlkit_pose_detection: ^0.9.0
  image: ^4.0.15
  google_mlkit_commons: ^0.5.0
  
  # UI 컴포넌트
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  
  # 상태 관리 및 저장소
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # 유틸리티
  intl: ^0.18.1
  vibration: ^1.8.1
  share_plus: ^7.2.1
  
  # 알림 및 시간
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  
  table_calendar: ^3.0.9
  
  image_picker: ^1.0.7
  permission_handler: ^10.4.5
  flutter_riverpod: ^2.4.9
  image_gallery_saver: ^2.0.3
  provider: ^6.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/splash_image.png
    - assets/images/camera_guide.png
    - assets/images/goal_success.png
    - assets/images/history_empty.png
    
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#42a5f5"
  image: assets/images/splash_icon.png
  android_12:
    image: assets/images/splash_icon.png
    icon_background_color: "#42a5f5"
  web: false
